### ISSUE TITLE
Mobile phones page hopping

### ISSUE THREAD

**Issue by SourceCodeplz** [guins/jQuery.scrollSections#5]
Hey man,
Its me again trying to get this plugin to work even better on mobile phones.
On some phones, it does work, but does not scroll section by section. It just scrolls like a normal page with the added difference that once you take your finger off the phone, it will stabilize itself to the section most visible.

The problem starts here, when stabilizing: the stabilization is not stopping, it just scrolls 1px up and then 1px down continuously.

Maybe its in the way it calculates the viewport, missing 1-2 pixels.

Let me know what you think.

**Comment by guins** [comment]
Hey Daniel,
No worries, I'm busy right now but I can probably have a look at it later next week.

Because you already open a feed couple of days ago, I will close this one so let's talk on the other one.

Don't hesitate to send me a pull request!
Cheers.
